language: c
sudo: false
addons:
  apt:
    packages:
      - cmake
      - uncrustify
      - colordiff
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
#    - os: osx
#      compiler: gcc
    - os: osx
      compiler: clang
script:
  # Print all environment variables to aid in CI development
  - uname -a
  - printenv
  # Print version and available CMake generators to aid in CI development
  - cmake --version
  - cmake --help
  # Perform out-of-source build
  - mkdir build
  - cd build
  # Perform CMake backend generation, build, and test
  - cmake ..
  - cmake --build . -- -j4
  - ctest --output-on-failure -C Debug -j4
  - etc/uncrustify_check.sh
